### ISSUE TITLE
Deep export?

### ISSUE THREAD

**Issue by jship** [tfausak/autoexporter#5]
Interested in adding support for deep exporting?

If so, I'll open a PR: ~https://github.com/jship/autoexporter/commit/ffd4caae348ad6045fe031a4231fcd29f085acc8~

**Comment by tfausak** [comment]
Thanks for opening this issue (and making the change)! 

I'm not sure that I want to add support for this. I typically use Autoexporter for avoiding modules like [this](https://github.com/tfausak/rattletrap/blob/2.5.0/library/Rattletrap/Primitive.hs). Can you give an example of where you need the deep re-exporting?

**Comment by jship** [comment]
I'm working on a [package](https://github.com/jship/pep) for parsing Windows .exe and .dll files and the nature of the nested records lends itself well to having the module hierarchy reflect the format spec.  Putting all the types in a single file for a project like this (or even multiple files under a `Types` folder)  makes it difficult to cross-reference against the spec doc.

I want users to be able to just import the top-level module and have access to everything in the package, so a deep approach with `autoexporter` would be convenient.

I updated the commit, https://github.com/jship/autoexporter/commit/ac262dd1baf70573fb6b198d9f7ab6c45354f483, to let the user optionally choose if they want deep re-exporting via `{-# OPTIONS_GHC -F -pgmF autoexporter -optF --deep #-}`.

If no option is specified, `autoexporter` should work just as before and only re-export immediate children.

**Comment by tfausak** [comment]
Ooh, I like that a lot! Can you go ahead and open a PR?

**Comment by jship** [comment]
Sounds good, thanks!
