### ISSUE TITLE
compile failures

### ISSUE THREAD

**Issue by hvr** [tfausak/autoexporter#7]
I just noticed compile failures, likely an inaccurate lower version bound on `directory`:

```
Configuring library for autoexporter-1.1.0..
Preprocessing library for autoexporter-1.1.0..
Building library for autoexporter-1.1.0..
[1 of 1] Compiling Autoexporter     ( source/library/Autoexporter.hs, /tmp/matrix-worker/1500734177/dist-newstyle/build/x86_64-linux/ghc-7.10.3/autoexporter-1.1.0/build/Autoexporter.o )

source/library/Autoexporter.hs:41:36:
    Not in scope: ‘Directory.listDirectory’
    Perhaps you meant one of these:
      ‘Directory.createDirectory’ (imported from System.Directory),
      ‘Directory.removeDirectory’ (imported from System.Directory),
      ‘Directory.renameDirectory’ (imported from System.Directory)

source/library/Autoexporter.hs:47:16:
    Not in scope: ‘Directory.listDirectory’
    Perhaps you meant one of these:
      ‘Directory.createDirectory’ (imported from System.Directory),
      ‘Directory.removeDirectory’ (imported from System.Directory),
      ‘Directory.renameDirectory’ (imported from System.Directory)
cabal: Failed to build autoexporter-1.1.0 (which is required by exe:autoexporter from autoexporter-1.1.0).

```

Btw, `autoexporter` seems to be one of those tools for which [`build-tool-depends`](http://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=build-tool-depends#pkg-field-build-tool-depends) was added to Cabal to help track build-time dependencies more accurately. So for a cabal component requiring `autoexporter`, you'd e.g. declare

    build-tool-depends: autoexporter:autoexporter ^>= 1.0

**Comment by tfausak** [comment]
> autoexporter seems to be one of those tools for which build-tool-depends was added to Cabal to help track build-time dependencies more accurately

Sure, but that only works on Cabal 2. When will that be released?

**Comment by hvr** [comment]
@tfausak real soon now(tm) :-)

PS: btw, 

```
Configuring library for autoexporter-1.1.1..
Preprocessing library for autoexporter-1.1.1..
Building library for autoexporter-1.1.1..
[1 of 1] Compiling Autoexporter     ( source/library/Autoexporter.hs, /tmp/matrix-worker/1500752723/dist-newstyle/build/x86_64-linux/ghc-7.8.4/autoexporter-1.1.1/build/Autoexporter.o )

source/library/Autoexporter.hs:53:12: Not in scope: ‘pure’

source/library/Autoexporter.hs:54:3: Not in scope: ‘pure’

source/library/Autoexporter.hs:54:10:
    Not in scope: ‘mconcat’
    Perhaps you meant ‘concat’ (imported from Prelude)
cabal: Failed to build autoexporter-1.1.1 (which is required by exe:autoexporter from autoexporter-1.1.1).

```

I've already fixed up the meta-data, see

- https://hackage.haskell.org/package/autoexporter-1.1.0/revisions/
- https://hackage.haskell.org/package/autoexporter-1.1.1/revisions/

please note that performing full-releases for what can be addressed by meta-data revisions is not recommended as it has mostly negative effects on the Hackage/Cabal ecosystem.
