### ISSUE TITLE
Autoexporter fails to open file

### ISSUE THREAD

**Issue by buggymcbugfix** [tfausak/autoexporter#8]
I get the following error for a file `src/MyPrelude.hs` with `{-# OPTIONS_GHC -F -pgmF autoexporter #-}` at the top.

```Building library for checker-0.1.0.0..
autoexporter: src/MyPrelude: getDirectoryContents:openDirStream: does not exist (No such file or directory)
`autoexporter' failed in phase `Haskell pre-processor'. (Exit code: 1)
Completed 2 action(s).
```

Any ideas?

**Comment by tfausak** [comment]
Sorry, I didn't see this issue until now! 

In your source tree, is `src/MyPrelude` a directory?

**Comment by buggymcbugfix** [comment]
No worries. Sorry for giving so little information when I first opened this issue. I'll look into this when I get back to the project I was trying to use this for. I'll close this issue for now and reopen if this happens again.
